### ISSUE TITLE
Escaped backslash within inline markup pairs not highlighted correctly

### ISSUE THREAD

**Issue by idnsunset** [marshallward/vim-restructuredtext#39] opened 2019-05-09 09:25 UTC
Suppose a piece of rst code like:

```rst
Press :kbd:`\\` or :kbd:`/` key.
```
I expected `` `\\` `` to be highlighted but I actually got `` `\\` or :kbd:` `` highlighted, which means that `` \\` `` does get skipped  in syntax region. 

I tried to modify the syntax file `rst.vim` to have  `` \` `` prepended with odd number of `\` not skip looking for the region end:

```rst
function! s:DefineInlineMarkup(name, start, middle, end)
  let middle = a:middle != "" ?
        \ (' skip=+\%(\\\)\@<!\%(\\\\\)*\\' . a:middle . '+') :
        \ ""
```

It seems to work in this case, but I'm not sure if it's sufficient to handle other complex situation.

**Comment by marshallward** [comment] 2019-05-09 11:21
Yeah, confirmed for me.  It seems that the syntax file regards `` \` `` as an escape character but reST does not.  

This is the first time I've looked at this line, so I still need to digest it, but will give your change a try and hopefully get back to you soon.  Thanks!

**Comment by marshallward** [comment] 2019-05-09 11:28
I am wondering it it's even correct to look for `\:middle:` as a general escape character.  I think it might be worth looking into this and selectively removing this character for specific inline markup tokens.  I'd like to sample this for a few others and see how it behaves in general.

**Comment by idnsunset** [comment] 2019-05-12 08:14
ReST does regard `` \` `` as an escaped character but the syntax file just doesn't consider the ending like `` \\` `` where the second backslash is escaped by the first.

**Comment by marshallward** [comment] 2019-05-12 20:22
Yes, you are right, sorry for my confusion.  It's the escaped backslash being falsely interpreted as an escape grave character.

Searching for three slashes ought to work, I'll test it out and see how it performs.

**Comment by marshallward** [comment] 2019-05-27 01:55
I'm sorry for the very long delay here.  Aside from the constraints on my time due to a recent overseas move, I have been wondering if there is a simpler solution here which would avoid use of `\@<!`, since it can be expensive and is invoked many times.

Looking at how this is handled in Python, it's far simpler and the otherwise identical `skip` definition appears to function correctly, without having to look for triple slashes:
```
137 syn region  pythonString matchgroup=pythonQuotes
138       \ start=+[uU]\=\z(['"]\)+ end="\z1" skip="\\\\\|\\\z1"
139       \ contains=pythonEscape,@Spell                     
```
The reST `start` and `end` are more complex, primarily because it's supporting these `char_left` and `char_right` tokens which seem to potentially encapsulate the highlighted regions.
```
 98   execute 'syn region rst' . a:name .                                          
 99         \ ' start=+' . a:char_left . '\zs' . a:start .                         
100         \ '\ze[^[:space:]' . a:char_right . a:start[strlen(a:start) - 1] . ']+' .
101         \ a:middle .                                                           
102         \ ' end=+\S' . a:end . '\ze\%($\|\s\|[''"’)\]}>/:.,;!?\\-]\)+' .       
103         \ ' contains=rstEscape'                                                
```
I'm honestly not sure what the purpose of this additional code is for, though I'm sure Niko added it for a good reason. (One of the perils of inheriting a syntax file...)

At the moment, if I strip out a lot of that complexity, then I seem to get the desired behavior:
```
104   execute 'syn region rst' . a:name .                                           
105         \ ' start=+' . a:start . '+'                                            
106         \ ' end=+' . a:end . '+'                                                
107         \ ' skip=+\\\\\|\\' . a:start . '+'                                     
108         \ ' contains=rstEscape'                                                 
```
But I don't yet know what we might be losing.

I will try to sit down and work this out.  If I get nowhere then I may just use your fix.  But I think it's worth trying to settle on a simpler implementation comparable to the implementation in Python if possible.

(As a side issue, it's been very easy to add highlighting of escape characters, which I've included in my local version and will push soon.)

**Comment by marshallward** [comment] 2019-05-27 02:41
wanted to add that I'm having better luck with this one:
```
syn match rstEscape +\\\\+
function! s:DefineOneInlineMarkup(name, start, middle, end, char_left, char_right)
  execute 'syn match rstEscape +\\' . a:start . '+ ' 
        \  . ' contained'

  execute 'syn region rst' . a:name .
        \ ' start=+' . a:char_left . '\zs' . a:start .
        \   '\ze[^[:space:]' . a:char_right . a:start[strlen(a:start) - 1] . ']+' .
        \ ' skip=+\\\\\|\\' . a:start . '+'
        \ ' end=+' . a:end . '+'
        \ ' contains=rstEscape'
endfunction
```
i.e. just removing this bit:
```
'\ze\%($\|\s\|[''"’)\]}>/:.,;!?\\-]\)+'
```

I've gone over the standard and I understand the purpose of the `char_left` and `char_right` now (reST limits the characters allowed prior to the inline, and requires specific pairs) but don't yet understand the purpose of that additional block in the `end` statement.  Will work through that one now...

**Comment by marshallward** [comment] 2019-05-28 01:43
quick followup: I appear to have a fix that works which moves the non-space header in `end='\S...'` and replaces it with a `skip ='+\s' . a:middle . '+\|...'` which appears to sort everything out.

BTW your fix did some some of the problems outlined above, but there were some other unsolved cases, which seem to be sorted out by changing the no-space+token ender into a space+token skip.  Will go over this change in some more detail and will update.

**Comment by marshallward** [comment] 2019-05-31 01:02
I've pushed a fix (f26f944) which appears to resolve the problem.  Could you give it a try when you get a chance?  If it's working for you then Ill send this to Bram.

**Comment by marshallward** [comment] 2019-06-04 13:56
Closing this issue for now, feel free to re-open if the problem still exists.

**Closed by marshallward** 2019-06-04 13:56 UTC

**Comment by idnsunset** [comment] 2019-06-17 15:36
Sorry for the late response, thanks for your hard work! I've tried out the fix, no problem found so far. Would you like to consider linking `rstEscape` group to the specific group depending on the inline markup name instead of `Special`? Thus we could get the correct highlight style . For example, linking `rstEscapeEmphasis` to `rstEmphasis`,

By the way, I find the answer about your question about the trailing `'\ze\%($\|\s\|[''"’)\]}>/:.,;!?\\-]\)'`. 
Here is the explanation quoted from http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-markup
>If the configuration setting simple-inline-markup is False (default), additional conditions apply to the characters "around" the inline markup:
>* Inline markup start-strings must start a text block or be immediately preceded by
>   - whitespace,
>   - one of the ASCII characters - : / ' " < ( [ {
>   - or a similar non-ASCII punctuation character. 
>* Inline markup end-strings must end a text block or be immediately followed by
>   - whitespace,
>   - one of the ASCII characters - . , : ; ! ? \ / ' " ) ] } >
>   - or a similar non-ASCII punctuation character.

**Comment by marshallward** [comment] 2019-06-17 15:46
Are you saying that you would prefer for the escaped characters to have the same highlight as the rest of the inline characters?  I added that partly because it seems pretty standard for most other syntax highlights, and also to make its presence explicit within the inline since they can be have unexpected effects for users.

But (assuming that I do understand) anything can be made optional, and we can add a flag to turn that off.

**Comment by idnsunset** [comment] 2019-06-18 17:59
Yes, that's exactly what I meant. I agree that your explanation make more sense, but I still expect the escaped characters not to be only rendered in different color but in italic or bold as well within emphasized or strongly emphasized text, which seems to make the highlight more consistent.

**Comment by marshallward** [comment] 2019-06-19 12:10
That seems very reasonable.  I have those features disabled so I don't usually think or notice them.

I'll try to find some time to implement it today.  Also feel free to send a patch if you can get it working.

**Comment by madjxatw** [comment] 2019-12-05 16:40
https://github.com/marshallward/vim-restructuredtext/commit/f26f94415688efbea8aa33396373e33068eb2e48 breaks inline literal rendering as described in #44 
 For ``C:\``, the `rstEscape.a:name` syntax match eats up the first the backtick. I add an `if` statement to exclude the inline literal from `rstEscape` to make it temporarily work for me.

```vim
  if a:start != '``'
    execute 'syn match rstEscape'.a:name.' +\\\\\|\\'.first.'+'.' contained'
    execute 'syn region rst' . a:name .
        \ ' start=+' . a:char_left . '\zs' . a:start .
        \ '\ze[^[:space:]' . a:char_right . a:start[strlen(a:start) - 1] . ']+' .
        \ a:middle .
        \ ' end=+' . a:end . '\ze\%($\|\s\|[''"’)\]}>/:.,;!?\\-]\)+' .
        \ ' contains=rstEscape' . a:name
    execute 'hi def link rstEscape'.a:name.' Special'
  else
    execute 'syn region rst' . a:name .
        \ ' start=+' . a:char_left . '\zs' . a:start .
        \ '\ze[^[:space:]' . a:char_right . a:start[strlen(a:start) - 1] . ']+' .
        \ a:middle .
        \ ' end=+' . a:end . '\ze\%($\|\s\|[''"’)\]}>/:.,;!?\\-]\)+'
  endif
```
